name: Build Documents
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Checkout Code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
      - name: Setup Typst
        if: ${{ steps.release.outputs.release_created }}
        uses: typst-community/setup-typst@v5
      - name: Setup Task
        if: ${{ steps.release.outputs.release_created }}
        uses: go-task/setup-task@v2
        with:
          version: 3.x
      - name: Install Fonts
        if: ${{ steps.release.outputs.release_created }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-ebgaramond \
            fonts-inter \
            fonts-alegreya-sans \
            fonts-bebas-neue
      - name: Compile Documents
        if: ${{ steps.release.outputs.release_created }}
        run: |
          task build VERSION="${{ steps.release.outputs.tag_name }}"
      - name: Release
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.release.outputs.tag_name }}"
          files: "*.pdf"
