name: Build resume document
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Fontist
        uses: fontist/setup-fontist@v2
      - name: Install Fonts
        run: |
          fontist install "Alegreya Sans"
          fontist install "Inter"
          fontist fontconfig update
      - name: Verify Fonts
        run: |
          fontist status "Alegreya Sans"
          fontist status "Inter"
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            TasmanVoseResume.typ
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} - ${{ env.DATE }}"
          files: TasmanVoseResume.pdf
